import Link from "next/link";
import ThemeToggle from "./components/theme-toggle";

const nav = [
  ["⌂", "Genel Bakış", "/"], ["✉", "Gelen Mesajlar", "/gelen-mesajlar"], ["◌", "Konuşmalar", "/konusmalar"],
  ["♙", "Müşteriler", "/musteriler"], ["ϟ", "Satış Fırsatları", "/satis-firsatlari"], ["◇", "Ürünler", "/urunler"],
  ["▥", "Raporlar & Analitik", "/raporlar"], ["◈", "AI Öneriler", "/ai-center"], ["◫", "Entegrasyonlar", "/entegrasyonlar"], ["⚙", "Ayarlar", "/ayarlar"]
];
const metrics = [
  ["●", "Toplam Görüşme", "356", "↑ %18.5"], ["♙", "Yeni Müşteri", "42", "↑ %21.2"], ["◎", "Satış Fırsatı", "28", "↑ %27.3"],
  ["↗", "Web Yönlendirme", "63", "↑ %16.7"], ["✦", "AI Çözüm Oranı", "%78", "↑ %12.4"], ["◉", "İnsan Müdahalesi", "8", "↓ %11.1"]
];
const conversations = [["🟢","Elif Kaya","Merhaba, pırlanta yüzük modelleri...","14:32"],["🟣","burcu_aksu","Bu bilekliğin fiyatı nedir?","14:28"],["🟢","Mehmet Demir","Kargom ne zaman gelir?","14:22"],["🟣","seda_altun","Sarı altın mı beyaz altın mı?","14:18"],["🟢","Ayşe Yıldız","Yüzük ölçümü nasıl alabilirim?","14:10"]];
const urgent = [["🟢","Hasan Kara","Şikayet","13:47"],["🟣","zeynep_inan","İade Talebi","13:15"],["🟢","Ahmet Yıldız","Kargo Sorusu","12:50"]];
const ops = [["🚚","Kargo Gecikmesi","3 sipariş gecikmiş durumda","10:20"],["◷","İade Talebi","2 yeni iade talebi var","09:15"],["▣","Ödeme Bekleniyor","5 sipariş ödemesi beklemede","08:40"]];

function Sidebar(){return <aside className="sidebar"><Link href="/" className="brand"><div className="brand-mark ai-logo">AI</div><div><div className="brand-title">KUYUMCU SATIŞ</div><div className="brand-sub">ASİSTANI</div></div></Link><Link href="/ayarlar" className="store"><div className="store-badge">LG</div><div><b>Luxe Gold</b><div className="store-sub">Kuyumculuk</div></div><span className="chev">⌄</span></Link><nav className="nav">{nav.map(([icon,label,href],i)=><Link key={label} href={href} className={i===0?"active":""}><span className="icon">{icon}</span><span>{label}</span>{label==="Gelen Mesajlar"&&<span className="badge">12</span>}{label==="Satış Fırsatları"&&<span className="badge">8</span>}</Link>)}</nav><div className="plan"><div className="eyebrow">MEVCUT PAKET</div><strong>Pro Gold</strong><div className="plan-row"><span>Sonraki fatura</span><span>20 Eylül</span></div><div className="plan-row"><span>Kullanım</span><span>%68</span></div><div className="meter"><i/></div><Link className="upgrade" href="/ayarlar">Paketi Yönet</Link></div></aside>}
function Panel({title,children,link}:{title:string;children:React.ReactNode;link?:string}){return <div className="panel"><div className="panel-title"><span>{title}</span></div><div className="panel-body">{children}</div>{link&&<Link className="all" href={link}>Tümünü Gör →</Link>}</div>}
function Activity(){const bars=[28,38,52,43,70,57,82,64,96,76,88,84,91,67,84,62,49,31,22];return <Panel title="AI Asistan Aktivitesi"><div className="chart">{bars.map((h,i)=><i className="bar" style={{height:`${h}%`}} key={i}/>)}<div className="axis"><span>00:00</span><span>04:00</span><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span><span>24:00</span></div></div></Panel>}
function Funnel(){return <Panel title="Satış Hunisi"><div className="funnel-wrap"><div className="funnel"><i/><i/><i/><i/></div><div className="funnel-data"><div><strong>356</strong><span>Görüşme</span></div><div><strong>128</strong><span>Ürün Önerildi</span></div><div><strong>63</strong><span>Web'e Yönlendirildi</span></div><div><strong>28</strong><span>Satışa Dönüştü</span></div></div></div><div className="conversion">Dönüşüm Oranı: %7.9</div></Panel>}
function Urgent(){return <Panel title="Yetkili Personel Acil Destek" link="/gelen-mesajlar"><div className="list">{urgent.map(([ic,n,t,time])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="item-time">{time}</span></div>)}</div></Panel>}
function Conversations(){return <Panel title="Canlı Müşteri Görüşmeleri" link="/gelen-mesajlar"><div className="list">{conversations.map(([ic,n,t,time])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="item-time">{time}</span></div>)}</div></Panel>}
function Lower(){return <div className="lower"><Conversations/><Panel title="Kargo & Operasyon Bildirimleri"><div className="list">{ops.map(([ic,n,t,time])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="item-time">{time}</span></div>)}</div><Link className="all" href="/raporlar">Tümünü Gör →</Link></Panel><Panel title="Entegrasyon & Veri Senkronizasyonu"><div className="list">{[["◉","WhatsApp Business","Bağlı · Aktif"],["◎","Instagram","Bağlı · Aktif"],["◉","Web Sitesi","Son senkronizasyon: 5 dk önce"],["▣","Ürün Verileri","Son senkronizasyon: 5 dk önce"]].map(([ic,n,t])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="ok">✓</span></div>)}</div><Link className="all" href="/entegrasyonlar">Tümünü Gör →</Link></Panel><Panel title="◉ AI Asistan Özeti"><div className="summary-big">Merhaba Ahmet! 👋</div><p className="summary-text">Bugün 356 görüşme gerçekleştirdim. 28 satış fırsatı yakaladım ve 63 müşteriyi web sitesine yönlendirdim.</p>{[["Otomatik Yanıtlanan","256"],["İnsan Devredilen","52"],["Satışa Dönüşen","28"]].map(([a,b])=><div className="summary-row" key={a}><span>{a}</span><strong>{b}</strong></div>)}</Panel></div>}
export default function Home(){return <div className="app"><Sidebar/><main className="main"><header className="topbar"><div className="topbar-date">1 Eylül 2026</div><ThemeToggle/><Link className="ghost notification" href="/bildirimler" aria-label="Bildirimler" title="Bildirimler">♢<span className="notification-badge">7</span></Link><Link className="ghost profile-top" href="/ayarlar?tab=kullanicilar" aria-label="Aktif kullanıcı"><span className="avatar avatar-top">👤</span><span className="profile-name">Ahmet Yılmaz</span></Link></header><section className="content"><div className="head"><div><div className="kicker">GENEL BAKIŞ</div><h1>Günaydın, Ahmet Bey 👋</h1><p>Bugünkü performansınızı ve AI satış asistanınızın aktivitelerini takip edin.</p></div><div className="filters"><Link className="filter" href="/raporlar">☷ Filtrele</Link></div></div><div className="metrics">{metrics.map(([ic,t,v,tr])=><div className="card metric" key={t}><div className="metric-top"><span className="metric-icon">{ic}</span><span>{t}</span></div><div className="metric-value">{v}</div><span className={tr.startsWith("↓")?"trend down":"trend"}>{tr}</span></div>)}</div><div className="grid"><Activity/><Funnel/><Urgent/></div><Lower/><div className="footer"><span>🔒 Tüm verileriniz güvende. ISO 27001 standartlarına uygun altyapı ile korunmaktadır.</span><span>Gizlilik Politikası　•　Kullanım Koşulları　•　Destek</span></div></section></main></div>}
