import Link from "next/link";

const nav = [
  ["⌂","Genel Bakış","/"],["✉","Gelen Kutusu","/gelen-kutusu","12"],["♙","Müşteriler","/musteriler"],["ϟ","Satış Fırsatları","/satis-firsatlari","8"],["◇","Ürünler","/urunler"],["▣","Stok Yönetimi","/stok"],["₺","Fiyat Motoru","/fiyat-motoru"],["✣","Kampanyalar","/kampanyalar"],["▥","Raporlar & Analitik","/raporlar"],["◈","AI Center","/ai-center"],["◫","Entegrasyonlar","/entegrasyonlar"],["⚙","Ayarlar","/ayarlar"],
] as const;

const metrics = [["●","Toplam Görüşme","356","↑ %18.5","Dün: 301"],["♙","Yeni Müşteri","42","↑ %21.2","Dün: 34"],["◎","Satış Fırsatı","28","↑ %27.3","Dün: 22"],["↗","Web Yönlendirme","63","↑ %16.7","Dün: 54"],["✦","AI Çözüm Oranı","%78","↑ %12.4","Dün: %70"],["◉","İnsan Müdahalesi","8","↓ %11.1","Dün: 9"]];
const chats=[["🟢","Elif Kaya","Merhaba, pırlanta yüzük modelleri...","14:32","2"],["🟣","burcu_aksu","Bu bilekliğin fiyatı nedir?","14:28","1"],["🟢","Mehmet Demir","Kargom ne zaman gelir?","14:22",""],["🟣","seda_altun","Sarı altın mı beyaz altın mı önerirsiniz?","14:18","3"],["🟢","Ayşe Yıldız","Yüzük ölçümü nasıl alabilirim?","14:10",""]];
const interventions=[["🟢","Hasan Kara","Şikayet","Ürünüm istediğim gibi gelmedi...","13:47"],["🟣","zeynep_inan","İade Talebi","Aldığım bilekliği iade etmek istiyorum.","13:15"],["🟢","Ahmet Yıldız","Kargo Sorusu","Kargom nerede, bilgi alabilir miyim?","12:50"]];
const operations=[["🚚","Kargo Gecikmesi","3 sipariş gecikmiş durumda","10:20"],["◷","İade Talebi","2 yeni iade talebi var","09:15"],["▣","Ödeme Bekleniyor","5 sipariş ödemesi beklemede","08:40"]];
const sync=[["◉","WhatsApp Business","Bağlı · Aktif"],["◎","Instagram","Bağlı · Aktif"],["◉","Web Sitesi","Son senkronizasyon: 5 dk önce"],["▣","Ürün Verileri","Son senkronizasyon: 5 dk önce"]];

function Sidebar(){return <aside className="sidebar"><div className="brand"><div className="brand-mark"><span>◇</span></div><div><div className="brand-title">KUYUMCU AI</div><div className="brand-sub">SATIŞ ASİSTANI</div></div></div><div className="store"><div className="store-badge">LG</div><div><div className="store-name">Luxe Gold</div><div className="store-sub">Kuyumculuk</div></div><span className="chev">⌄</span></div><nav className="nav">{nav.map(([icon,label,href,badge])=><Link key={label} href={href} className={href==="/"?"active":""}><span className="icon">{icon}</span><span>{label}</span>{badge&&<span className="badge">{badge}</span>}</Link>)}</nav><div className="plan"><div className="eyebrow">MEVCUT PAKET</div><strong>Pro Gold</strong><div className="plan-row"><span>Sonraki fatura tarihi</span><span>20 Eylül 2026</span></div><div className="plan-row" style={{marginTop:10}}><span>Kullanım</span><span>%68</span></div><div className="meter"><i/></div><button className="upgrade">Paketi Yükselt</button></div><div className="user"><div className="avatar">👤</div><div><b>Ahmet Yılmaz</b><small>Yönetici</small></div><span className="chev">›</span></div></aside>}
function Header(){return <header className="topbar"><button className="gold-btn">＋ Hızlı İşlem</button><button className="ghost">ⓘ Yardım</button><button className="ghost">♧</button></header>}
function MetricCards(){return <div className="metrics">{metrics.map(([icon,title,value,trend,prev])=><div className="card metric" key={title}><div className="metric-top"><span className="metric-icon">{icon}</span><span>{title}</span></div><div className="metric-value">{value}</div><span className={trend.startsWith("↓")?"trend down":"trend"}>{trend}</span><span style={{color:"#69737a",fontSize:11,marginLeft:10}}>{prev}</span></div>)}</div>}
function Activity(){const heights=[28,38,52,43,70,57,82,64,96,76,102,84,91,67,84,62,49,31,22];return <div className="panel"><div className="panel-title">AI Asistan Aktivitesi (Gün içinde)<button className="ghost" style={{padding:"5px 9px",fontSize:11}}>Günlük⌄</button></div><div className="panel-body"><div className="chart">{heights.map((h,i)=><i className="bar" style={{height:`${h}%`}} key={i}/>) }<div className="axis"><span>00:00</span><span>04:00</span><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span><span>24:00</span></div></div></div></div>}
function Funnel(){return <div className="panel"><div className="panel-title">Satış Hunisi</div><div className="panel-body"><div className="funnel-wrap"><div className="funnel"><i/><i/><i/><i/></div><div className="funnel-data"><div><strong>356</strong><span>Görüşme</span></div><div><strong>128</strong><span>Ürün Önerildi</span></div><div><strong>63</strong><span>Web'e Yönlendirildi</span></div><div><strong>28</strong><span>Satışa Dönüştü</span></div></div></div><div className="conversion">Dönüşüm Oranı: %7.9</div></div></div>}
function ChatList(){return <div className="panel"><div className="panel-title">Canlı Müşteri Görüşmeleri <span style={{color:"#65d38f"}}>● 12</span></div><div className="panel-body list">{chats.map(([ic,n,t,time,count])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="item-time">{time}</span>{count&&<span className="item-count">{count}</span>}</div>)}</div><a className="all" href="/gelen-kutusu">Tümünü Gör →</a></div>}
function Lower(){return <div className="lower"><div className="panel"><div className="panel-title">İnsan Müdahalesi Gerekenler <span className="badge">5</span></div><div className="panel-body list">{interventions.map(([ic,n,tag,t,time])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n} <small style={{background:"#653431",padding:"2px 5px",borderRadius:4,color:"#ffaaa5"}}>{tag}</small></strong><p>{t}</p></div><span className="item-time">{time}</span></div>)}</div><a className="all" href="/gelen-kutusu">Tümünü Gör →</a></div><div className="panel"><div className="panel-title">Kargo & Operasyon Bildirimleri <span className="badge">4</span></div><div className="panel-body list">{operations.map(([ic,n,t,time])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="item-time">{time}</span></div>)}</div><a className="all" href="/stok">Tümünü Gör →</a></div><div className="panel"><div className="panel-title">Entegrasyon & Veri Senkronizasyonu</div><div className="panel-body list">{sync.map(([ic,n,t])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span style={{color:"#65d38f"}}>✓</span></div>)}</div><a className="all" href="/entegrasyonlar">Tümünü Gör →</a></div><div className="panel ai-summary"><div className="panel-title ai-title">◉ AI Asistan Özeti</div><div className="panel-body"><div className="summary-big">Merhaba Ahmet! 👋</div><p style={{color:"#aeb5b9",lineHeight:1.5}}>Bugün 356 görüşme gerçekleştirdim. 28 satış fırsatı yakaladım ve 63 müşteriyi web sitesine yönlendirdim.</p><div className="summary-row"><span>Öğrenilen Yeni Bilgi</span><strong>24</strong></div><div className="summary-row"><span>Otomatik Yanıtlanan</span><strong>256</strong></div><div className="summary-row"><span>İnsan Devredilen</span><strong>52</strong></div><div className="summary-row"><span>Satışa Dönüşen</span><strong>28</strong></div></div><a className="all" href="/ai-center">AI Center'a Git →</a></div></div>}
export default function Home(){return <div className="app"><Sidebar/><main className="main"><Header/><section className="content"><div className="head"><div><div className="kicker">GENEL BAKIŞ</div><h1>Günaydın, Ahmet Bey 👋</h1><p>Bugünkü performansınızı ve AI satış asistanınızın aktivitelerini takip edin.</p></div><div className="filters"><button className="filter">▣ 1 Eylül 2026⌄</button><button className="filter">☷ Filtrele</button></div></div><MetricCards/><div className="grid"><Activity/><Funnel/><ChatList/></div><Lower/><div className="footer"><span>🔒 Tüm verileriniz güvende. ISO 27001 standartlarına uygun altyapı ile korunmaktadır.</span><span>Gizlilik Politikası　•　Kullanım Koşulları　•　Destek</span></div></section></main></div>}
