import Link from "next/link";

const nav = [
  ["⌂", "Genel Bakış", "/"], ["✉", "Gelen Kutusu", "/gelen-kutusu"], ["♙", "Müşteriler", "/musteriler"],
  ["ϟ", "Satış Fırsatları", "/satis-firsatlari"], ["◇", "Ürünler", "/urunler"], ["▣", "Stok Yönetimi", "/stok"],
  ["₺", "Fiyat Motoru", "/fiyat-motoru"], ["✣", "Kampanyalar", "/kampanyalar"], ["▥", "Raporlar & Analitik", "/raporlar"],
  ["◈", "AI Center", "/ai-center"], ["◫", "Entegrasyonlar", "/entegrasyonlar"], ["⚙", "Ayarlar", "/ayarlar"]
];
const metrics = [
  ["●", "Toplam Görüşme", "356", "↑ %18.5"], ["♙", "Yeni Müşteri", "42", "↑ %21.2"],
  ["◎", "Satış Fırsatı", "28", "↑ %27.3"], ["↗", "Web Yönlendirme", "63", "↑ %16.7"],
  ["✦", "AI Çözüm Oranı", "%78", "↑ %12.4"], ["◉", "İnsan Müdahalesi", "8", "↓ %11.1"]
];
const conversations = [
  ["🟢", "Elif Kaya", "Merhaba, pırlanta yüzük modelleri...", "14:32"], ["🟣", "burcu_aksu", "Bu bilekliğin fiyatı nedir?", "14:28"],
  ["🟢", "Mehmet Demir", "Kargom ne zaman gelir?", "14:22"], ["🟣", "seda_altun", "Sarı altın mı beyaz altın mı?", "14:18"],
  ["🟢", "Ayşe Yıldız", "Yüzük ölçümü nasıl alabilirim?", "14:10"]
];
const ops = [["🚚", "Kargo Gecikmesi", "3 sipariş gecikmiş durumda", "10:20"], ["◷", "İade Talebi", "2 yeni iade talebi var", "09:15"], ["▣", "Ödeme Bekleniyor", "5 sipariş ödemesi beklemede", "08:40"]];

function Sidebar() {
  return <aside className="sidebar">
    <div className="brand"><div className="brand-mark"><span>◇</span></div><div><div className="brand-title">KUYUMCU AI</div><div className="brand-sub">SATIŞ ASİSTANI</div></div></div>
    <div className="store"><div className="store-badge">LG</div><div><b>Luxe Gold</b><div className="store-sub">Kuyumculuk</div></div><span className="chev">⌄</span></div>
    <nav className="nav">{nav.map(([icon, label, href], i) => <Link key={label} href={href} className={i === 0 ? "active" : ""}><span className="icon">{icon}</span><span>{label}</span>{i === 1 && <span className="badge">12</span>}{i === 3 && <span className="badge">8</span>}</Link>)}</nav>
    <div className="plan"><div className="eyebrow">MEVCUT PAKET</div><strong>Pro Gold</strong><div className="plan-row"><span>Sonraki fatura</span><span>20 Eylül</span></div><div className="plan-row"><span>Kullanım</span><span>%68</span></div><div className="meter"><i /></div><button className="upgrade">Paketi Yükselt</button></div>
    <div className="user"><div className="avatar">👤</div><div><b>Ahmet Yılmaz</b><small>Yönetici</small></div><span className="chev">›</span></div>
  </aside>;
}
function Panel({title, children, link}:{title:string,children:React.ReactNode,link?:string}) { return <div className="panel"><div className="panel-title"><span>{title}</span></div><div className="panel-body">{children}</div>{link && <Link className="all" href={link}>Tümünü Gör →</Link>}</div>; }
function Activity() { const bars=[28,38,52,43,70,57,82,64,96,76,88,84,91,67,84,62,49,31,22]; return <Panel title="AI Asistan Aktivitesi"><div className="chart">{bars.map((h,i)=><i className="bar" style={{height:`${h}%`}} key={i}/>)}<div className="axis"><span>00:00</span><span>04:00</span><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span><span>24:00</span></div></div></Panel>; }
function Funnel(){return <Panel title="Satış Hunisi"><div className="funnel-wrap"><div className="funnel"><i/><i/><i/><i/></div><div className="funnel-data"><div><strong>356</strong><span>Görüşme</span></div><div><strong>128</strong><span>Ürün Önerildi</span></div><div><strong>63</strong><span>Web'e Yönlendirildi</span></div><div><strong>28</strong><span>Satışa Dönüştü</span></div></div></div><div className="conversion">Dönüşüm Oranı: %7.9</div></Panel>;}
function Conversations(){return <Panel title="Canlı Müşteri Görüşmeleri" link="/gelen-kutusu"><div className="list">{conversations.map(([ic,n,t,time])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="item-time">{time}</span></div>)}</div></Panel>;}
function Lower(){return <div className="lower"><Panel title="İnsan Müdahalesi Gerekenler"><div className="list">{[["🟢","Hasan Kara","Şikayet","13:47"],["🟣","zeynep_inan","İade Talebi","13:15"],["🟢","Ahmet Yıldız","Kargo Sorusu","12:50"]].map(([ic,n,t,time])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="item-time">{time}</span></div>)}</div><Link className="all" href="/gelen-kutusu">Tümünü Gör →</Link></Panel><Panel title="Kargo & Operasyon Bildirimleri"><div className="list">{ops.map(([ic,n,t,time])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="item-time">{time}</span></div>)}</div><Link className="all" href="/stok">Tümünü Gör →</Link></Panel><Panel title="Entegrasyon & Veri Senkronizasyonu"><div className="list">{[["◉","WhatsApp Business","Bağlı · Aktif"],["◎","Instagram","Bağlı · Aktif"],["◉","Web Sitesi","Son senkronizasyon: 5 dk önce"],["▣","Ürün Verileri","Son senkronizasyon: 5 dk önce"]].map(([ic,n,t])=><div className="item" key={n}><span className="channel">{ic}</span><div className="item-main"><strong>{n}</strong><p>{t}</p></div><span className="ok">✓</span></div>)}</div><Link className="all" href="/entegrasyonlar">Tümünü Gör →</Link></Panel><Panel title="◉ AI Asistan Özeti"><div className="summary-big">Merhaba Ahmet! 👋</div><p className="summary-text">Bugün 356 görüşme gerçekleştirdim. 28 satış fırsatı yakaladım ve 63 müşteriyi web sitesine yönlendirdim.</p>{[["Otomatik Yanıtlanan","256"],["İnsan Devredilen","52"],["Satışa Dönüşen","28"]].map(([a,b])=><div className="summary-row" key={a}><span>{a}</span><strong>{b}</strong></div>)}</Panel></div>;}
export default function Home(){return <div className="app"><Sidebar/><main className="main"><header className="topbar"><button className="gold-btn">＋ Hızlı İşlem</button><button className="ghost">ⓘ Yardım</button><button className="ghost">♧</button></header><section className="content"><div className="head"><div><div className="kicker">GENEL BAKIŞ</div><h1>Günaydın, Ahmet Bey 👋</h1><p>Bugünkü performansınızı ve AI satış asistanınızın aktivitelerini takip edin.</p></div><div className="filters"><button className="filter">▣ 1 Eylül 2026⌄</button><button className="filter">☷ Filtrele</button></div></div><div className="metrics">{metrics.map(([ic,t,v,tr])=><div className="card metric" key={t}><div className="metric-top"><span className="metric-icon">{ic}</span><span>{t}</span></div><div className="metric-value">{v}</div><span className={tr.startsWith("↓")?"trend down":"trend"}>{tr}</span></div>)}</div><div className="grid"><Activity/><Funnel/><Conversations/></div><Lower/><div className="footer"><span>🔒 Tüm verileriniz güvende. ISO 27001 standartlarına uygun altyapı ile korunmaktadır.</span><span>Gizlilik Politikası　•　Kullanım Koşulları　•　Destek</span></div></section></main></div>;}
